name: build
on: push
jobs:
  compile:
    runs-on: ${{ matrix.os }}-latest
    strategy:
      fail-fast: false
      matrix:
        os: [windows, ubuntu, macos]
    steps:
    - uses: actions/checkout@v1
      with:
        ref: refs/heads/master
        submodules : recursive
    - uses: actboy168/setup-luamake@master
    - if: runner.os != 'Linux'
      run: luamake
    - if: runner.os == 'Linux'
      run: luamake -gcc gcc-8 -gxx g++-8
    - uses: actions/upload-artifact@v1.0.0
      with:
        name: lua-language-server
        path: bin
